package ovh.glitchlabs.ornamentum.datagen;

import net.minecraft.core.Holder;
import net.minecraft.core.HolderLookup;
import net.minecraft.data.loot.BlockLootSubProvider;
import net.minecraft.world.flag.FeatureFlags;
import net.minecraft.world.level.block.Block;
import ovh.glitchlabs.ornamentum.blocks.ModBlocks;

import java.util.Set;

public class ModBlockLootTableProvider extends BlockLootSubProvider {
    protected ModBlockLootTableProvider(HolderLookup.Provider registries) {
        super(Set.of(), FeatureFlags.REGISTRY.allFlags(), registries);
    }

    @Override
    protected void generate() {

        dropSelf(ModBlocks.DUCK.get());
        dropSelf(ModBlocks.FAN_BLOCK.get());
        dropSelf(ModBlocks.REDSTONE_POWERED_FAN_BLOCK.get());
        dropSelf(ModBlocks.BABY_TURTLE.get());
        dropSelf(ModBlocks.LINK_BLOCK.get());
        dropSelf(ModBlocks.IRON_SHELF.get());

        dropSelf(ModBlocks.OBSIDIAN_BRICKS.get());
        dropSelf(ModBlocks.OBSIDIAN_TILES.get());
        dropSelf(ModBlocks.CRACKED_OBSIDIAN_BRICKS.get());
        dropSelf(ModBlocks.CRACKED_OBSIDIAN_TILES.get());
        dropSelf(ModBlocks.POLISHED_OBSIDIAN.get());

        dropSelf(ModBlocks.WHITE_FLAG.get());
        dropSelf(ModBlocks.ORANGE_FLAG.get());
        dropSelf(ModBlocks.MAGENTA_FLAG.get());
        dropSelf(ModBlocks.LIGHT_BLUE_FLAG.get());
        dropSelf(ModBlocks.YELLOW_FLAG.get());
        dropSelf(ModBlocks.LIME_FLAG.get());
        dropSelf(ModBlocks.PINK_FLAG.get());
        dropSelf(ModBlocks.GRAY_FLAG.get());
        dropSelf(ModBlocks.LIGHT_GRAY_FLAG.get());
        dropSelf(ModBlocks.CYAN_FLAG.get());
        dropSelf(ModBlocks.PURPLE_FLAG.get());
        dropSelf(ModBlocks.BLUE_FLAG.get());
        dropSelf(ModBlocks.BROWN_FLAG.get());
        dropSelf(ModBlocks.GREEN_FLAG.get());
        dropSelf(ModBlocks.RED_FLAG.get());
        dropSelf(ModBlocks.BLACK_FLAG.get());

        dropSelf(ModBlocks.AUSTRIA_FLAG.get());
        dropSelf(ModBlocks.BOUVET_ISLAND_FLAG.get());
        dropSelf(ModBlocks.CANADA_FLAG.get());
        dropSelf(ModBlocks.CHINA_FLAG.get());
        dropSelf(ModBlocks.DENMARK_FLAG.get());
        dropSelf(ModBlocks.FINLAND_FLAG.get());
        dropSelf(ModBlocks.FRANCE_FLAG.get());
        dropSelf(ModBlocks.GERMANY_FLAG.get());
        dropSelf(ModBlocks.GREECE_FLAG.get());
        dropSelf(ModBlocks.HUNGARY_FLAG.get());
        dropSelf(ModBlocks.ICELAND_FLAG.get());
        dropSelf(ModBlocks.INDIA_FLAG.get());
        dropSelf(ModBlocks.IRELAND_FLAG.get());
        dropSelf(ModBlocks.ITALY_FLAG.get());
        dropSelf(ModBlocks.JAPAN_FLAG.get());
        dropSelf(ModBlocks.LATVIA_FLAG.get());
        dropSelf(ModBlocks.NETHERLANDS_FLAG.get());
        dropSelf(ModBlocks.SWEDEN_FLAG.get());
        dropSelf(ModBlocks.SWITZERLAND_FLAG.get());
        dropSelf(ModBlocks.UNITED_KINGDOM_FLAG.get());
        dropSelf(ModBlocks.UNITED_STATES_FLAG.get());

        dropSelf(ModBlocks.AGENDER_FLAG.get());
        dropSelf(ModBlocks.AROACE_FLAG.get());
        dropSelf(ModBlocks.AROMANTIC_FLAG.get());
        dropSelf(ModBlocks.ASEXUAL_FLAG.get());
        dropSelf(ModBlocks.BISEXUAL_FLAG.get());
        dropSelf(ModBlocks.DEMIROMANTIC_FLAG.get());
        dropSelf(ModBlocks.DEMISEXUAL_FLAG.get());
        dropSelf(ModBlocks.GAY_MEN_FLAG.get());
        dropSelf(ModBlocks.GENDERFLUID_FLAG.get());
        dropSelf(ModBlocks.GENDERQUEER_FLAG.get());
        dropSelf(ModBlocks.INTERSEX_FLAG.get());
        dropSelf(ModBlocks.LESBIAN_FLAG.get());
        dropSelf(ModBlocks.NON_BINARY_FLAG.get());
        dropSelf(ModBlocks.OMNISEXUAL_FLAG.get());
        dropSelf(ModBlocks.PANSEXUAL_FLAG.get());
        dropSelf(ModBlocks.PRIDE_FLAG.get());
        dropSelf(ModBlocks.PROGRESS_PRIDE_FLAG.get());
        dropSelf(ModBlocks.TRANS_FLAG.get());


        dropSelf(ModBlocks.RED_PATTERN_BLOCK.get());
        dropSelf(ModBlocks.RED_PATTERN_BLOCK_STAIRS.get());
        dropSelf(ModBlocks.RED_PATTERN_BLOCK_SLAB.get());

        dropSelf(ModBlocks.WHITE_PATTERN_BLOCK.get());
        dropSelf(ModBlocks.WHITE_PATTERN_BLOCK_STAIRS.get());
        dropSelf(ModBlocks.WHITE_PATTERN_BLOCK_SLAB.get());

        dropSelf(ModBlocks.ORANGE_PATTERN_BLOCK.get());
        dropSelf(ModBlocks.ORANGE_PATTERN_BLOCK_STAIRS.get());
        dropSelf(ModBlocks.ORANGE_PATTERN_BLOCK_SLAB.get());

        dropSelf(ModBlocks.MAGENTA_PATTERN_BLOCK.get());
        dropSelf(ModBlocks.MAGENTA_PATTERN_BLOCK_STAIRS.get());
        dropSelf(ModBlocks.MAGENTA_PATTERN_BLOCK_SLAB.get());

        dropSelf(ModBlocks.LIGHT_BLUE_PATTERN_BLOCK.get());
        dropSelf(ModBlocks.LIGHT_BLUE_PATTERN_BLOCK_STAIRS.get());
        dropSelf(ModBlocks.LIGHT_BLUE_PATTERN_BLOCK_SLAB.get());

        dropSelf(ModBlocks.YELLOW_PATTERN_BLOCK.get());
        dropSelf(ModBlocks.YELLOW_PATTERN_BLOCK_STAIRS.get());
        dropSelf(ModBlocks.YELLOW_PATTERN_BLOCK_SLAB.get());

        dropSelf(ModBlocks.LIME_PATTERN_BLOCK.get());
        dropSelf(ModBlocks.LIME_PATTERN_BLOCK_STAIRS.get());
        dropSelf(ModBlocks.LIME_PATTERN_BLOCK_SLAB.get());

        dropSelf(ModBlocks.PINK_PATTERN_BLOCK.get());
        dropSelf(ModBlocks.PINK_PATTERN_BLOCK_STAIRS.get());
        dropSelf(ModBlocks.PINK_PATTERN_BLOCK_SLAB.get());

        dropSelf(ModBlocks.GRAY_PATTERN_BLOCK.get());
        dropSelf(ModBlocks.GRAY_PATTERN_BLOCK_STAIRS.get());
        dropSelf(ModBlocks.GRAY_PATTERN_BLOCK_SLAB.get());

        dropSelf(ModBlocks.LIGHT_GRAY_PATTERN_BLOCK.get());
        dropSelf(ModBlocks.LIGHT_GRAY_PATTERN_BLOCK_STAIRS.get());
        dropSelf(ModBlocks.LIGHT_GRAY_PATTERN_BLOCK_SLAB.get());

        dropSelf(ModBlocks.CYAN_PATTERN_BLOCK.get());
        dropSelf(ModBlocks.CYAN_PATTERN_BLOCK_STAIRS.get());
        dropSelf(ModBlocks.CYAN_PATTERN_BLOCK_SLAB.get());

        dropSelf(ModBlocks.PURPLE_PATTERN_BLOCK.get());
        dropSelf(ModBlocks.PURPLE_PATTERN_BLOCK_STAIRS.get());
        dropSelf(ModBlocks.PURPLE_PATTERN_BLOCK_SLAB.get());

        dropSelf(ModBlocks.BLUE_PATTERN_BLOCK.get());
        dropSelf(ModBlocks.BLUE_PATTERN_BLOCK_STAIRS.get());
        dropSelf(ModBlocks.BLUE_PATTERN_BLOCK_SLAB.get());

        dropSelf(ModBlocks.BROWN_PATTERN_BLOCK.get());
        dropSelf(ModBlocks.BROWN_PATTERN_BLOCK_STAIRS.get());
        dropSelf(ModBlocks.BROWN_PATTERN_BLOCK_SLAB.get());

        dropSelf(ModBlocks.GREEN_PATTERN_BLOCK.get());
        dropSelf(ModBlocks.GREEN_PATTERN_BLOCK_STAIRS.get());
        dropSelf(ModBlocks.GREEN_PATTERN_BLOCK_SLAB.get());

        dropSelf(ModBlocks.BLACK_PATTERN_BLOCK.get());
        dropSelf(ModBlocks.BLACK_PATTERN_BLOCK_STAIRS.get());
        dropSelf(ModBlocks.BLACK_PATTERN_BLOCK_SLAB.get());

        dropSelf(ModBlocks.POOL_TILES.get());
        dropSelf(ModBlocks.POOL_TILES1.get());

        dropSelf(ModBlocks.POOL_TILES_STAIRS.get());
        dropSelf(ModBlocks.POOL_TILES1_STAIRS.get());

        dropSelf(ModBlocks.POOL_TILES_SLAB.get());
        dropSelf(ModBlocks.POOL_TILES1_SLAB.get());

        dropSelf(ModBlocks.MESH_IRON.get());

        dropSelf(ModBlocks.IRON_GRATE.get());
        dropSelf(ModBlocks.GOLD_GRATE.get());
        dropSelf(ModBlocks.DIAMOND_GRATE.get());
        dropSelf(ModBlocks.NETHERITE_GRATE.get());
        dropSelf(ModBlocks.AMETHYST_GRATE.get());
        dropSelf(ModBlocks.OBSIDIAN_GRATE.get());

        dropSelf(ModBlocks.LIME_GLOW_BLOCK.get());
        dropSelf(ModBlocks.WHITE_GLOW_BLOCK.get());
        dropSelf(ModBlocks.LIGHT_GRAY_GLOW_BLOCK.get());
        dropSelf(ModBlocks.GRAY_GLOW_BLOCK.get());
        dropSelf(ModBlocks.BLACK_GLOW_BLOCK.get());
        dropSelf(ModBlocks.BROWN_GLOW_BLOCK.get());
        dropSelf(ModBlocks.RED_GLOW_BLOCK.get());
        dropSelf(ModBlocks.ORANGE_GLOW_BLOCK.get());
        dropSelf(ModBlocks.YELLOW_GLOW_BLOCK.get());
        dropSelf(ModBlocks.GREEN_GLOW_BLOCK.get());
        dropSelf(ModBlocks.CYAN_GLOW_BLOCK.get());
        dropSelf(ModBlocks.LIGHT_BLUE_GLOW_BLOCK.get());
        dropSelf(ModBlocks.BLUE_GLOW_BLOCK.get());
        dropSelf(ModBlocks.PURPLE_GLOW_BLOCK.get());
        dropSelf(ModBlocks.MAGENTA_GLOW_BLOCK.get());
        dropSelf(ModBlocks.PINK_GLOW_BLOCK.get());

        dropSelf(ModBlocks.LIME_GLOW_BLOCK_STAIRS.get());
        dropSelf(ModBlocks.WHITE_GLOW_BLOCK_STAIRS.get());
        dropSelf(ModBlocks.LIGHT_GRAY_GLOW_BLOCK_STAIRS.get());
        dropSelf(ModBlocks.GRAY_GLOW_BLOCK_STAIRS.get());
        dropSelf(ModBlocks.BLACK_GLOW_BLOCK_STAIRS.get());
        dropSelf(ModBlocks.BROWN_GLOW_BLOCK_STAIRS.get());
        dropSelf(ModBlocks.RED_GLOW_BLOCK_STAIRS.get());
        dropSelf(ModBlocks.ORANGE_GLOW_BLOCK_STAIRS.get());
        dropSelf(ModBlocks.YELLOW_GLOW_BLOCK_STAIRS.get());
        dropSelf(ModBlocks.GREEN_GLOW_BLOCK_STAIRS.get());
        dropSelf(ModBlocks.CYAN_GLOW_BLOCK_STAIRS.get());
        dropSelf(ModBlocks.LIGHT_BLUE_GLOW_BLOCK_STAIRS.get());
        dropSelf(ModBlocks.BLUE_GLOW_BLOCK_STAIRS.get());
        dropSelf(ModBlocks.PURPLE_GLOW_BLOCK_STAIRS.get());
        dropSelf(ModBlocks.MAGENTA_GLOW_BLOCK_STAIRS.get());
        dropSelf(ModBlocks.PINK_GLOW_BLOCK_STAIRS.get());

        dropSelf(ModBlocks.LIME_GLOW_BLOCK_SLAB.get());
        dropSelf(ModBlocks.WHITE_GLOW_BLOCK_SLAB.get());
        dropSelf(ModBlocks.LIGHT_GRAY_GLOW_BLOCK_SLAB.get());
        dropSelf(ModBlocks.GRAY_GLOW_BLOCK_SLAB.get());
        dropSelf(ModBlocks.BLACK_GLOW_BLOCK_SLAB.get());
        dropSelf(ModBlocks.BROWN_GLOW_BLOCK_SLAB.get());
        dropSelf(ModBlocks.RED_GLOW_BLOCK_SLAB.get());
        dropSelf(ModBlocks.ORANGE_GLOW_BLOCK_SLAB.get());
        dropSelf(ModBlocks.YELLOW_GLOW_BLOCK_SLAB.get());
        dropSelf(ModBlocks.GREEN_GLOW_BLOCK_SLAB.get());
        dropSelf(ModBlocks.CYAN_GLOW_BLOCK_SLAB.get());
        dropSelf(ModBlocks.LIGHT_BLUE_GLOW_BLOCK_SLAB.get());
        dropSelf(ModBlocks.BLUE_GLOW_BLOCK_SLAB.get());
        dropSelf(ModBlocks.PURPLE_GLOW_BLOCK_SLAB.get());
        dropSelf(ModBlocks.MAGENTA_GLOW_BLOCK_SLAB.get());
        dropSelf(ModBlocks.PINK_GLOW_BLOCK_SLAB.get());

        dropSelf(ModBlocks.WHITE_WOOL_STAIRS.get());
        dropSelf(ModBlocks.ORANGE_WOOL_STAIRS.get());
        dropSelf(ModBlocks.MAGENTA_WOOL_STAIRS.get());
        dropSelf(ModBlocks.LIGHT_BLUE_WOOL_STAIRS.get());
        dropSelf(ModBlocks.YELLOW_WOOL_STAIRS.get());
        dropSelf(ModBlocks.LIME_WOOL_STAIRS.get());
        dropSelf(ModBlocks.PINK_WOOL_STAIRS.get());
        dropSelf(ModBlocks.GRAY_WOOL_STAIRS.get());
        dropSelf(ModBlocks.LIGHT_GRAY_WOOL_STAIRS.get());
        dropSelf(ModBlocks.CYAN_WOOL_STAIRS.get());
        dropSelf(ModBlocks.PURPLE_WOOL_STAIRS.get());
        dropSelf(ModBlocks.BLUE_WOOL_STAIRS.get());
        dropSelf(ModBlocks.BROWN_WOOL_STAIRS.get());
        dropSelf(ModBlocks.GREEN_WOOL_STAIRS.get());
        dropSelf(ModBlocks.RED_WOOL_STAIRS.get());
        dropSelf(ModBlocks.BLACK_WOOL_STAIRS.get());

        dropSelf(ModBlocks.WHITE_WOOL_SLAB.get());
        dropSelf(ModBlocks.ORANGE_WOOL_SLAB.get());
        dropSelf(ModBlocks.MAGENTA_WOOL_SLAB.get());
        dropSelf(ModBlocks.LIGHT_BLUE_WOOL_SLAB.get());
        dropSelf(ModBlocks.YELLOW_WOOL_SLAB.get());
        dropSelf(ModBlocks.LIME_WOOL_SLAB.get());
        dropSelf(ModBlocks.PINK_WOOL_SLAB.get());
        dropSelf(ModBlocks.GRAY_WOOL_SLAB.get());
        dropSelf(ModBlocks.LIGHT_GRAY_WOOL_SLAB.get());
        dropSelf(ModBlocks.CYAN_WOOL_SLAB.get());
        dropSelf(ModBlocks.PURPLE_WOOL_SLAB.get());
        dropSelf(ModBlocks.BLUE_WOOL_SLAB.get());
        dropSelf(ModBlocks.BROWN_WOOL_SLAB.get());
        dropSelf(ModBlocks.GREEN_WOOL_SLAB.get());
        dropSelf(ModBlocks.RED_WOOL_SLAB.get());
        dropSelf(ModBlocks.BLACK_WOOL_SLAB.get());

        dropSelf(ModBlocks.WHITE_BRICKS.get());
        dropSelf(ModBlocks.ORANGE_BRICKS.get());
        dropSelf(ModBlocks.MAGENTA_BRICKS.get());
        dropSelf(ModBlocks.LIGHT_BLUE_BRICKS.get());
        dropSelf(ModBlocks.YELLOW_BRICKS.get());
        dropSelf(ModBlocks.LIME_BRICKS.get());
        dropSelf(ModBlocks.PINK_BRICKS.get());
        dropSelf(ModBlocks.GRAY_BRICKS.get());
        dropSelf(ModBlocks.LIGHT_GRAY_BRICKS.get());
        dropSelf(ModBlocks.CYAN_BRICKS.get());
        dropSelf(ModBlocks.PURPLE_BRICKS.get());
        dropSelf(ModBlocks.BLUE_BRICKS.get());
        dropSelf(ModBlocks.BROWN_BRICKS.get());
        dropSelf(ModBlocks.GREEN_BRICKS.get());
        dropSelf(ModBlocks.RED_BRICKS.get());
        dropSelf(ModBlocks.BLACK_BRICKS.get());

        dropSelf(ModBlocks.WHITE_BRICKS_STAIRS.get());
        dropSelf(ModBlocks.ORANGE_BRICKS_STAIRS.get());
        dropSelf(ModBlocks.MAGENTA_BRICKS_STAIRS.get());
        dropSelf(ModBlocks.LIGHT_BLUE_BRICKS_STAIRS.get());
        dropSelf(ModBlocks.YELLOW_BRICKS_STAIRS.get());
        dropSelf(ModBlocks.LIME_BRICKS_STAIRS.get());
        dropSelf(ModBlocks.PINK_BRICKS_STAIRS.get());
        dropSelf(ModBlocks.GRAY_BRICKS_STAIRS.get());
        dropSelf(ModBlocks.LIGHT_GRAY_BRICKS_STAIRS.get());
        dropSelf(ModBlocks.CYAN_BRICKS_STAIRS.get());
        dropSelf(ModBlocks.PURPLE_BRICKS_STAIRS.get());
        dropSelf(ModBlocks.BLUE_BRICKS_STAIRS.get());
        dropSelf(ModBlocks.BROWN_BRICKS_STAIRS.get());
        dropSelf(ModBlocks.GREEN_BRICKS_STAIRS.get());
        dropSelf(ModBlocks.RED_BRICKS_STAIRS.get());
        dropSelf(ModBlocks.BLACK_BRICKS_STAIRS.get());

        dropSelf(ModBlocks.WHITE_BRICKS_SLAB.get());
        dropSelf(ModBlocks.ORANGE_BRICKS_SLAB.get());
        dropSelf(ModBlocks.MAGENTA_BRICKS_SLAB.get());
        dropSelf(ModBlocks.LIGHT_BLUE_BRICKS_SLAB.get());
        dropSelf(ModBlocks.YELLOW_BRICKS_SLAB.get());
        dropSelf(ModBlocks.LIME_BRICKS_SLAB.get());
        dropSelf(ModBlocks.PINK_BRICKS_SLAB.get());
        dropSelf(ModBlocks.GRAY_BRICKS_SLAB.get());
        dropSelf(ModBlocks.LIGHT_GRAY_BRICKS_SLAB.get());
        dropSelf(ModBlocks.CYAN_BRICKS_SLAB.get());
        dropSelf(ModBlocks.PURPLE_BRICKS_SLAB.get());
        dropSelf(ModBlocks.BLUE_BRICKS_SLAB.get());
        dropSelf(ModBlocks.BROWN_BRICKS_SLAB.get());
        dropSelf(ModBlocks.GREEN_BRICKS_SLAB.get());
        dropSelf(ModBlocks.RED_BRICKS_SLAB.get());
        dropSelf(ModBlocks.BLACK_BRICKS_SLAB.get());

        dropSelf(ModBlocks.AMETIST_BRICKS.get());
        dropSelf(ModBlocks.AMETIST_BRICKS_STAIRS.get());
        dropSelf(ModBlocks.AMETIST_BRICKS_SLAB.get());

        dropSelf(ModBlocks.SMOOTH_BASALT_BRICKS.get());
        dropSelf(ModBlocks.SMOOTH_BASALT_BRICKS_STAIRS.get());
        dropSelf(ModBlocks.SMOOTH_BASALT_BRICKS_SLAB.get());

        dropSelf(ModBlocks.PURPUR_BRICKS.get());
        dropSelf(ModBlocks.PURPUR_BRICKS_STAIRS.get());
        dropSelf(ModBlocks.PURPUR_BRICKS_SLAB.get());

        dropSelf(ModBlocks.SMOOTH_BASALT_BRICKS.get());
        dropSelf(ModBlocks.SMOOTH_BASALT_BRICKS_STAIRS.get());
        dropSelf(ModBlocks.SMOOTH_BASALT_BRICKS_SLAB.get());

        dropSelf(ModBlocks.POLISHED_ANDESITE_BRICKS.get());
        dropSelf(ModBlocks.POLISHED_ANDESITE_BRICKS_STAIRS.get());
        dropSelf(ModBlocks.POLISHED_ANDESITE_BRICKS_SLAB.get());

        dropSelf(ModBlocks.POLISHED_DIORITE_BRICKS.get());
        dropSelf(ModBlocks.POLISHED_DIORITE_BRICKS_STAIRS.get());
        dropSelf(ModBlocks.POLISHED_DIORITE_BRICKS_SLAB.get());

        dropSelf(ModBlocks.POLISHED_GRANITE_BRICKS.get());
        dropSelf(ModBlocks.POLISHED_GRANITE_BRICKS_STAIRS.get());
        dropSelf(ModBlocks.POLISHED_GRANITE_BRICKS_SLAB.get());


        //dropSelf(ModBlocks.OBSIDIAN_BRICKS.get());
        dropWhenSilkTouch(ModBlocks.LIME_GLOW_STAINED_GLASS.get());
        dropWhenSilkTouch(ModBlocks.WHITE_GLOW_STAINED_GLASS.get());
        dropWhenSilkTouch(ModBlocks.GRAY_GLOW_STAINED_GLASS.get());
        dropWhenSilkTouch(ModBlocks.LIGHT_GRAY_GLOW_STAINED_GLASS.get());
        dropWhenSilkTouch(ModBlocks.BLACK_GLOW_STAINED_GLASS.get());
        dropWhenSilkTouch(ModBlocks.BROWN_GLOW_STAINED_GLASS.get());
        dropWhenSilkTouch(ModBlocks.RED_GLOW_STAINED_GLASS.get());
        dropWhenSilkTouch(ModBlocks.ORANGE_GLOW_STAINED_GLASS.get());
        dropWhenSilkTouch(ModBlocks.YELLOW_GLOW_STAINED_GLASS.get());
        dropWhenSilkTouch(ModBlocks.GREEN_GLOW_STAINED_GLASS.get());
        dropWhenSilkTouch(ModBlocks.CYAN_GLOW_STAINED_GLASS.get());
        dropWhenSilkTouch(ModBlocks.LIGHT_BLUE_GLOW_STAINED_GLASS.get());
        dropWhenSilkTouch(ModBlocks.BLUE_GLOW_STAINED_GLASS.get());
        dropWhenSilkTouch(ModBlocks.PURPLE_GLOW_STAINED_GLASS.get());
        dropWhenSilkTouch(ModBlocks.MAGENTA_GLOW_STAINED_GLASS.get());
        dropWhenSilkTouch(ModBlocks.PINK_GLOW_STAINED_GLASS.get());

    }

    @Override
    protected Iterable<Block> getKnownBlocks() {
        return ModBlocks.BLOCKS.getEntries().stream().map(Holder::value)::iterator;
    }
}
